language: cpp

matrix:
  include:

    # - os: linux
    #   compiler: clang        

    # - os: linux
    #   compiler: g++

    # - os: osx

    - os: windows
      env:
      - CC="/c/Program Files/LLVM/bin/clang"
      - CXX="/c/Program Files/LLVM/bin/clang++"

script:
  - ./benchmark/setup.sh
  - ./benchmark/run.sh
