language: cpp

matrix:
  include:

    - os: linux
      compiler: 
        - clang        
        - g++

    - os: osx

    - os: windows
      compiler: 
        - msvc
        - clang

script:
  - ./benchmark/setup.sh
  - ./benchmark/run.sh
