language: cpp
dist: xenial

matrix:
  include:

    - os: windows
      compiler: clang++
      generator: "MinGW Makefiles"
      env:
      - CC="/c/Program Files/LLVM/bin/clang"
      - CXX="/c/Program Files/LLVM/bin/clang++"
      - CC_FOR_BUILD="/c/Program Files/LLVM/bin/clang"
      - CXX_FOR_BUILD="/c/Program Files/LLVM/bin/clang++"

script:
  - ./benchmark/setup.sh
  - ./benchmark/run.sh
