language: cpp

matrix:
  include:

    - os: linux
      compiler: clang     

    - os: linux
      compiler: g++

    - os: osx

    - os: windows
      compiler: msvc

    - os: windows
      compiler: clang

    - os: windows
      compiler: g++

script:
  - ./benchmark/setup.sh
  - ./benchmark/run.sh
