language: cpp

matrix:
  include:

    - os: linux
      compiler: clang        

    - os: linux
      compiler: g++

    - os: osx

    - os: windows

script:
  - ./benchmark/setup.sh
  - ./benchmark/run.sh
